FROM node:14.17.3-alpine3.14

RUN apk add dumb-init

ENV NODE_ENV development

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm install --ignore-scripts
# If you are building your code for production
# RUN npm ci --only=production

COPY --chown=node:node . .

USER node
